# Generated by Django 5.2.6 on 2025-09-22 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lang_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_dest', to='translator.language')),
                ('lang_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_src', to='translator.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranslateText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_number', models.IntegerField()),
                ('sentence_src', models.TextField()),
                ('sentence_translated', models.TextField()),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='translator.translator')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionTranslator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='translator.translatetext')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='translator.translator')),
            ],
        ),
    ]
